### ISSUE TITLE
Discard Old Build only takes one package name. 

### ISSUE THREAD

**Issue by amullens2** [jfrog/artifactory-azure-devops-extension#119]
Need to include a Loop for the build name so you can pass in more then one package name in a pipeline that passes in multiple projects.

**Comment by eyalbe4** [comment]
@amullens2,
I'm not sure I understand the request. Can you please elaborate more and maybe add an example? What do you refer to as "package name"?
Thanks

**Comment by eyalbe4** [comment]
@amullens2,
Did you see my follow up question for your request?
