### ISSUE TITLE
Support regexp=true for Windows

### ISSUE THREAD

**Issue by AngelloMaggio** [jfrog/artifactory-azure-devops-extension#120]
Hi Team,

It seems that starting with version 1.27.0 (was working with 1.26.2) we stopped supporting regexp=true for Windows as per commit:
https://github.com/jfrog/artifactory-vsts-extension/commit/6a99fb043d9ebcbd1ca0bc252802bf0fd7af14c7

Are there plans to support regexp for Windows in the near future?

Thanks!

**Comment by michaelhuebschmannkuka** [comment]
regex worked just fine for previous versions of this task (with jfrog-cli 1.26), and also with the newest jfrog-cli when using it directly. Would be great to be able to use it again!

**Comment by eyalbe4** [comment]
@AngelloMaggio and @michaelhuebschmannkuka,
@RobiNino fixed this issue in https://github.com/jfrog/artifactory-vsts-extension/pull/128. The fix has just been released as part of version 1.8.3.
You feedback would be greatly appreciated.

**Comment by michaelhuebschmannkuka** [comment]
We could verify that with version 1.9.2 of the task using jfrog-cli 1.35.3 the regex with windows now works again.
Thanks a lot!

**Comment by KUGA2** [comment]
One little drawback though (no need to fix, just keep it in mind):
Backslashes must be escaped (as usual in Regexes). When you use a Azure DevOps Variables, that contain windows paths with Backslashes, this will still fail.
