### ISSUE TITLE
Support --insecure-tls flag for generic upload

### ISSUE THREAD

**Issue by eumikhailov** [jfrog/artifactory-azure-devops-extension#121]
Hi,

There is no way to set up --insecure-tls in pipeline task.
Can You add parameter to set up --insecure-tls?

**Comment by eumikhailov** [comment]
Hi @eyalbe4, 
This feature is useful for self-signed certs or corporate domain certs.

Can you consider this feature?

**Comment by eyalbe4** [comment]
@eumikhailov,
We intend to add this functionality soon.

**Comment by bennettagross** [comment]
Alternatively, you can set either of the following environment variables to control node's behavior at the agent level to get the same effect:

NODE_EXTRA_CA_CERTS =/path/to/your-domain-cas-or-certs.pem
NODE_TLS_REJECT_UNAUTHORIZED = 0

**Comment by eyalbe4** [comment]
@bennettagross,
Your suggested solution will help only for requests that are sent using nodeJS APIs. I think that @eumikhailov was referring to the *--insecure-tls* option exposed by JFrog CLI. We are planning to add this option to many of the Artifactory tasks, which rely on JFrog CLI behind the scenes. The plan is to deliver this in a few weeks time.

**Comment by eumikhailov** [comment]
@eyalbe4 @bennettagross
Yes, I'm using JFrog CLI from vsts task.
Thank you for your help, waiting for the implementation of new the functional :smiley:

**Comment by eyalbe4** [comment]
@eumikhailov,
The insecure TLS option is available as part of the latest release. You can see it as part of the **Advanced** section in the *Artifactory Generic Upload* and *Artifactory Generic Download* tasks.
Looking forward to your feedback for it.

**Comment by eumikhailov** [comment]
@eyalbe4 
Thank You, new version 2.* works fine!
