### ISSUE TITLE
x509: certificate signed by unknown authority error when windows agent is used

### ISSUE THREAD

**Issue by dbuschi** [jfrog/artifactory-azure-devops-extension#122]
Connecting to our artifactory causes a **Certificate Error: x509: certificate signed by unknown authority** when using a windows agent (I use **windows latest**). But it works with the Ubuntu agent (**ubuntu-latest**).

There have been similar issues (e.g. 44 and 88) raised and closed previously, but the problem is still very much alive.

Regards,
Dominic Buschi

**Comment by wulfland** [comment]
I have the same problem on windows server 2019. Not all public authorities are in the list of public authorities. You can verify this by running `gci Cert:\CurrentUser\AuthRoot\` or ` gci Cert:\LocalMachine\AuthRoot\`. My solution was to install the root certificates on the agent.

**Comment by eyalbe4** [comment]
Thanks so much for posting this solution @wulfland!
@dbuschi, can you please let us know if installing the root certificates on the agent resolve the issue?

**Comment by dbuschi** [comment]
Hi @wulfland 
Thanks for your reply! Just for clarification: Does that mean that you are running a self-hosted agent which you can configure as you like? Or is it possible to install a certificate on a managed agent (i.e. windows latest)?

**Comment by wulfland** [comment]
Hi @dbuschi. Yes, I use a self-hosted agent and installed the certificates there. I've not found a way to install the certificates on windows-latest. I tried with PowerShell and `import-certificate` but access was denied. I try to find out at Microsoft if this is a bug from windows server of if this is a permanent thing (maybe for security?). If I can figure anything out I'll let you know. Until then, the only option I see, is to run a self-hosted agent.

**Comment by dbuschi** [comment]
thanks again, @wulfland, this was the quickest response (even if it wasn't the answer I was looking for) I ever got to a question :-).

**Comment by wulfland** [comment]
UPDATE: I just found a way to use windows-latest. I use certutil to import the certificates at runtime. The PowerShell cmdlet Import-Certificate did no work - but certutil works. Here is my yaml snippet:
```
- script: | 
    certutil -f -addstore root certs\quovadis_rca_der.cer
    certutil -f -addstore root certs\quovadis_rca2_der.cer
    certutil -f -addstore root certs\quovadis_rca3_der.cer
    certutil -f -addstore root certs\quovadis_rcag3_der.cer
    certutil -f -addstore root certs\quovadis_rca2g3_der.cer
    certutil -f -addstore root certs\quovadis_rca3g3_der.cer
  displayName: 'Install Quo Vadis Root CA'
```
Not a ideal solution, but a temporary workaround.

**Comment by wulfland** [comment]
I added a more detailed description  in my blog: https://writeabout.net/2020/03/25/x509-certificate-signed-by-unknown-authority/ 
 
If you have any additions (maybe a more detailed error description from you?), let me know. I will add it.

**Comment by wulfland** [comment]
I filed an issue [here](https://github.com/actions/virtual-environments/issues/628)

**Comment by wulfland** [comment]
@dbuschi - the issue should be resolved: https://github.com/actions/virtual-environments/issues/628
Try again.

**Comment by fpiesche** [comment]
The workaround of manually installing the missing root CA certificate as part of the pipeline has worked for us as well.

**Comment by eyalbe4** [comment]
Thank you everyone for raising the issue and sharing the solutions here!
@dbuschi - Do you think this issue can be closed?

**Comment by dbuschi** [comment]
Closing it: Workaround described above. Thanks all for your help!
