### ISSUE TITLE
Generic Upload Task can't upload as Maven Artifact

### ISSUE THREAD

**Issue by andydkelly-ig** [jfrog/artifactory-azure-devops-extension#146]
Is there a way of having the Generic Upload task upload a file as a Maven artifact and generate a POM file?

**Comment by yahavi** [comment]
@andydkelly-ig,
Although you can upload an artifact to a Maven repository in Generic Upload task, it can't generate a POM for you. As the name of the tasks implies, this task can only upload files to Artifactory.

If it's relevant - you can generate POMs using the new [Gradle Task](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-TriggeringGradleBuilds) with `Deploy Maven descriptors` checked:
![image](https://user-images.githubusercontent.com/11367982/78271870-60fa4980-7515-11ea-8c8e-756d882aca75.png)


If you still have questions, please elaborate more about your use case and we'll do our best to help.

**Comment by eyalbe4** [comment]
@andydkelly-ig,
I'm closing this issue for now, but do let us know if you wish to discuss this further.
