### ISSUE TITLE
Artifactory Python Task

### ISSUE THREAD

**Issue by mohammadtibi** [jfrog/artifactory-azure-devops-extension#154]
Similar to our offerings for NPM, Docker, Maven, Go, etc, it would be ideal to have a Python Task as well to allow for the gathering of Build Info on Python builds + later on scan with Xray after the build info is published.

**Comment by m01** [comment]
#83 would offer a workaround

**Comment by eyalbe4** [comment]
#83 has been released in version 1.10.0.

**Comment by talarian1** [comment]
Hi @mohammadtibi and @m01 ,
The new Artifactory Pip task is included in the last release 1.11.0.
The relevant documentation can be found [here](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-TriggeringPythonBuildsUsingPip).
We'll appreciate any feedback.
