### ISSUE TITLE
NuGet support is not available on Linux hosts

### ISSUE THREAD

**Issue by TheMagoo73** [jfrog/artifactory-azure-devops-extension#159]
Is it possible to add support for NuGet operations when using Linux hosts? We're using .Net Core on Linux extensively, so this would be a big win for us. Looking at the code, it seems like it should be possible using the .Net Core/NuGet CLI for Linux.

**Comment by bartsipes** [comment]
PR #163 is adding support for this.

**Comment by RobiNino** [comment]
Hi @TheMagoo73  @bartsipes ,
NuGet task is supported on Mac & Linux agents as of task version 1.10.0.
We'd appreciate your feedback for it.
