### ISSUE TITLE
Artifactory Nuget Push does not allow custom path within repository

### ISSUE THREAD

**Issue by bartsipes** [jfrog/artifactory-azure-devops-extension#167]
The Artifactory Nuget task when set to Push does not provide a way to specify a path within a repository. 

For example, when I use the CommandLine task to push the Nuget package, I can specify the following:
```
nuget push $(NuGetPublishFilename).nupkg  -s $(NuGetUrl)/$(NuGetPublishFilename) -k $(NuGetApiKey)
```

This will allow a new package "MyCoolPackage.1.8.0.nupkg" to show up under the "MyCoolPackage" folder in the selected repository. With the Artifactory Nuget task, I can only select the repository and then all packages that are published are dropped under that repo at that root folder level which is very hard to manage. Please add a way that we can set a folder path under the selected repository.

**Comment by MightyJay** [comment]
Yes, I really need this as well. The [NuGet Repositories documentation](https://www.jfrog.com/confluence/display/JFROG/NuGet+Repositories#NuGetRepositories-LocalRepositoryLayout) advises to store NuGet packages inside folders, but says it is up to the developer to correctly deploy packages into the corresponding folder. So it's weird there is no way to actually supply this info to the plugin.

As a workaround I've been using the command line task as well, but this requires to add the API key to be added to each task, which is not scalable, and I cannot use the build info feature. Perhaps using the Artifactory Generic Upload task might be a workaround, but I would like to see it in the NuGet push task.

**Comment by eyalbe4** [comment]
Thanks for sharing this requirement @bartsipes and @MightyJay!
We'll definitely add this.

**Comment by yahavi** [comment]
@bartsipes @MightyJay,
This functionality is added in the latest Artifactory Azure DevOps extension - 1.11.0:
![image](https://user-images.githubusercontent.com/11367982/99387765-365ed480-28dd-11eb-9313-1d4aa0ed8e4a.png)

We'd appreciate your feedback for that.

**Comment by MightyJay** [comment]
@yahavi great, thank you! I just did a quick check and it seems to work fine: the package is uploaded in the path as I have supplied in the build task. (Note: I only checked the classic editor and not yet a YAML build, but I believe that should work too).

As a workaround I have been using the generic artifact uploader, but for NuGet package uploads this is a nicer solution. So thanks again!

**Comment by eyalbe4** [comment]
Thanks for the confirmation @MightyJay.
