### ISSUE TITLE
npm test fails with "Repository ado-extension-test-nuget-remote does not exist"

### ISSUE THREAD

**Issue by SimonAlling** [jfrog/artifactory-azure-devops-extension#194]
**Describe the bug**

I'm trying to run the tests locally, but `npm test` fails:

```
  JFrog Artifactory Extension Tests
    1) "before all" hook


  0 passing (2s)
  1 failing

  1) JFrog Artifactory Extension Tests
       "before all" hook:
     Error: Server responded to http://localhost:8081/artifactory/api/repositories/ado-extension-test-nuget-virtual-1599733507 with status code 400:
{
  "errors" : [ {
    "status" : 400,
    "message" : "Repository ado-extension-test-nuget-remote does not exist\n"
  } ]
}
      at Response.getBody (node_modules/http-response-object/lib/index.js:41:23)
      at createRepo (testUtils.js:289:101)
      at createTestRepositories (testUtils.js:166:5)
      at Object.initTests (testUtils.js:98:5)
      at Context.before (tests.js:24:19)
```

**To Reproduce**

Clone the repo, set the `ADO_` environment variables properly and run `npm test` as described in the readme.

**Expected behavior**

I expected the tests to pass.

**Versions**
- Artifactory Azure DevOps extension version: 1.10.2 (based on the Git tag)
- Agent operating system: Ubuntu 20.04
- JFrog Artifactory version: 7.7.3

**Additional context**
I installed Artifactory like this:

```bash
docker run --name artifactory -v ${JFROG_HOME}/artifactory/var/:/var/opt/jfrog/artifactory -d -p 8081:8081 -p 8082:8082 docker.bintray.io/jfrog/artifactory-pro:latest
```

**Comment by SimonAlling** [comment]
I should add that `export ADO_ARTIFACTORY_SKIP_TESTS=maven,gradle,npm,go,nuget,dotnet,conan,docker` didn't help, and that the tests passed (with said value for `ADO_ARTIFACTORY_SKIP_TESTS`) once I created `ado-extension-test-nuget-remote` manually.

**Comment by RobiNino** [comment]
Hi @SimonAlling ,
Thanks for reporting this issue. 
The tests suite couldn't create a remote nuget repository due to [RTFACT-10628](https://www.jfrog.com/jira/browse/RTFACT-10628) and [RTFACT-21536](https://www.jfrog.com/jira/browse/RTFACT-21536). Since these issues are now resolved, we should definitely add the repository creation to the tests init.
Thanks!

**Comment by RobiNino** [comment]
A NuGet remote repository will now be created by the tests suite.
Thanks @SimonAlling
