### ISSUE TITLE
How to upload to jfrog without appending "agent path directory"

### ISSUE THREAD

**Issue by koteshbhupathi** [jfrog/artifactory-azure-devops-extension#195]
Hello Team,

We started implementing  Jfrog enterprise integrating with Azure devops (CI-CD)., we are using "generic-upload" for CI to publish the artifacts. i need your advise on below screenshot i want to discard the agentpath like example 

Currently Repo path is saved as in JFROG : pulsetcrpacific-generic-nonprod/D:/a/1/s/WSM.PulseTech.root/WSM.PulseTech.Web/obj/Release/Package/PackageTmp/ (all files with folders)

What i wanted to achieve to publish in jfrog repository like :  pulsetcrpacific-generic-nonprod/PackageTmp/(all files and folders.)

Below are my File spec configuration:

{
  "files": [
    {
      "pattern":"$(Build.Repository.LocalPath)\WSM.PulseTech.root\WSM.PulseTech.Web\obj\Release\Package\",
      "flat" : "false",
      "target": "pulsetcrpacific-generic-nonprod/"
    }
  ]
}

![image](https://user-images.githubusercontent.com/56534334/93096871-8b565280-f6c2-11ea-9780-ede144c04126.png)

**Comment by RobiNino** [comment]
Hi @koteshbhupathi ,
Thanks for reaching out.
You can achieve your desired functionality using [Placeholders](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingPlaceholders).

Try changing your file spec to:
```    
"files": [
        {
            "pattern": "$(Build.Repository.LocalPath)\WSM.PulseTech.root\WSM.PulseTech.Web\obj\Release\Package\(*)",
            "target": "pulsetcrpacific-generic-nonprod/{1}",
            "flat": "true"
        }
    ]
```

Let me know if this works for you.

**Comment by koteshbhupathi** [comment]
Hi Robi,

Let me change that pipeline and update you.

Thanks
Kotesh

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by koteshbhupathi** [comment]
> 
> 
> Hi @koteshbhupathi ,
> Thanks for reaching out.
> You can achieve your desired functionality using [Placeholders](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingPlaceholders).
> 
> Try changing your file spec to:
> 
> ```
> "files": [
>         {
>             "pattern": "$(Build.Repository.LocalPath)\WSM.PulseTech.root\WSM.PulseTech.Web\obj\Release\Package\(*)",
>             "target": "pulsetcrpacific-generic-nonprod/{1}",
>             "flat": "true"
>         }
>     ]
> ```
> 
> Let me know if this works for you.

This is really perfect ,awesome ,what i was looking for Robi. i kept "Flat=false" because i have folder structure to copied inside as is.
I pushed the artificatory with aritifcatory build info like (Build name$(Build.DefinitionName) and buildnumber $(Build.BuildNumber).

please help me How can i download this in CD pipeline (generic download) with buildname and buildnumber using filespec.


![image](https://user-images.githubusercontent.com/56534334/93114290-0bd37e00-f6d8-11ea-82f6-9f41ad39ddbb.png)
![image](https://user-images.githubusercontent.com/56534334/93114404-2f96c400-f6d8-11ea-989f-d161eeb9ad96.png)
![image](https://user-images.githubusercontent.com/56534334/93114794-af249300-f6d8-11ea-8dea-7fdbbefe9549.png)

**Comment by RobiNino** [comment]
Im glad to hear that helped, @koteshbhupathi .
I suggest you leave flat=true, since the placeholder takes the full path that matches the wildcard (the result will not be flat).

See the [file specs documentation](https://www.jfrog.com/confluence/display/JFROG/Using+File+Specs#UsingFileSpecs-DownloadSpecSchema) to learn about more about the possible fields.
To download by build, set the `build` field accordingly.

**Comment by koteshbhupathi** [comment]
> 
> 
> Im glad to hear that helped, @koteshbhupathi .
> I suggest you leave flat=true, since the placeholder takes the full path that matches the wildcard (the result will not be flat).
> 
> See the [file specs documentation](https://www.jfrog.com/confluence/display/JFROG/Using+File+Specs#UsingFileSpecs-DownloadSpecSchema) to learn about more about the possible fields.
> To download by build, set the `build` field accordingly.

Thanks Robi.

i am trying to download the aritifact which i have upload in repo path "pulsetcrpacific-generic-nonprod/PackageTmp/"

i just want to download only PackageTmp directory (which contains my files and folders to be deployed). i dont want the repo  full path "pulsetcrpacific-generic-nonprod" to download in the CD agent default working directory $(System.DefaultWorkingDirectory).

i am using the file spec in below


{
  "files": [
    {
      "pattern": "pulsetcrpacific-generic-nonprod/",        
      "build" :  "JFROG-upload/$(Build.BuildNumber)",
      "target" : "$(System.DefaultWorkingDirectory)\{1}"
    }
  ]
}

**Comment by RobiNino** [comment]
@koteshbhupathi,
The `pattern` field can be set to a specific path ("pulsetcrpacific-generic-nonprod/PackageTmp/").
You can also use wildcards to help you control which files are affected ("pulsetcrpacific-generic-nonprod/PackageTmp/*.zip" - will only download artifacts with zip extension).

**Comment by RobiNino** [comment]
Hi @koteshbhupathi ,
Im closing this issue for now, do let us know if you need any further assistance.
Thanks
