### ISSUE TITLE
Build Promotion fails on JFrog Platform

### ISSUE THREAD

**Issue by HgDorn** [jfrog/artifactory-azure-devops-extension#198]
**Describe the bug**
The Azure Integration Task "Artifactory Publish Build Info" seem to use wrong pathes for the JFrog Platform.

![image](https://user-images.githubusercontent.com/71664544/93804870-2e6d1600-fc47-11ea-999d-253bf1fdbbd7.png)

The task  uploads successfully but JFrog Platform does not find the file location in repositiory afterwards - even though the artifacts can be manually found in the target repo location.

![image](https://user-images.githubusercontent.com/71664544/93805167-9e7b9c00-fc47-11ea-8b95-fb85504a5baa.png)

![image](https://user-images.githubusercontent.com/71664544/93804719-01206800-fc47-11ea-970f-86b1f400b477.png)

As a result the artifacts cannot be promoted to the next stage. The files are not found.
The same pipeline and its tasks worked fine with Artifactory 6.x but fails on JFrog platform.

**To Reproduce**
1. use generic upload task and check "collect build info"
2. use publish build info task
3. use JFrog PLatform cloud instance
4. check build info in Jfrog platform as shown by screenshots above

**Expected behavior**
The file path is given in build info of jfrog platform and the build promotion works.

![image](https://user-images.githubusercontent.com/71664544/93805949-bacc0880-fc48-11ea-864c-4eca57c15505.png)

**Versions**
- Artifactory Generic Upload task version 2.10.2
- Artifactory Publish Build Info 1.10.2
- JFrog CLI version: 1.38.4
- [AGENT_OS] --> [Windows_NT]
- [AGENT_OSARCHITECTURE] --> [X64]

**Comment by HgDorn** [comment]
Probably not a bug, but incorrect usage on our part ... I'm currently reviewing this and will report here

**Comment by HgDorn** [comment]
Suddenly the issue disappeared. But we also disabled the "Discard Build Tasks" in Azure a few days ago. This could be a cause. We are investigating this further.

**Comment by eyalbe4** [comment]
@HgDorn,
Was this issue resolved for you?

**Comment by HgDorn** [comment]
The issue did not appear again. So i will close it.
