### ISSUE TITLE
Artifactory NuGet restore is unable to handle spaces in Destination directory

### ISSUE THREAD

**Issue by shilpakallaganad19** [jfrog/artifactory-azure-devops-extension#199]
**Problem description:**
Artifactory NuGet restore , Version  : 2.10.0 is unable to handle spaces in Destination directory (under advance section).
For Example when we specify the Destination Directory as ‘path\to\the directory\packages’ it failed with following error:

##[error]Error: Command failed: jfrog rt nuget restore test.sln -NoCache -PackagesDirectory E:\\build_test-shilpa\\1\\test\\path\\to\\the directory\\packages -Verbosity Detailed --build-name="test-shilpa" --build-number="1"

*Expected solution**
We would request to enable the ability of passing a directory path with space in it so that the above error can be avoided in windows servers path. In case the folders are different for each build then using short path as a work around is not efficient.

**Comment by RobiNino** [comment]
Hi @shilpakallaganad19 ,
Thanks for reporting this issue.
Extension version 1.11.1 was recently released and includes a fix.
We'd appreciate your feedback for it.

**Comment by eyalbe4** [comment]
@shilpakallaganad19,
I'm closing this issue for now, but please let us know if you're still experiencing this issue.
