### ISSUE TITLE
Error: Cannot find module 'azure-pipelines-task-lib/task' with latest version

### ISSUE THREAD

**Issue by mrgandra** [jfrog/artifactory-azure-devops-extension#204]
There was a latest version of JFrog Artifactory extension 1.10.3 and its breaking all our builds

**Comment by RobiNino** [comment]
Hi @mrgandra , 
Thanks for reporting this issue.
We are aware of it and working to fix it ASAP.

**Comment by AceHack** [comment]
Having the same issue, please fix ASAP

**Comment by AceHack** [comment]
Is there a workaround we can use now!!

**Comment by mrgandra** [comment]
The latest version 2.10.4 is also broken still

**Comment by AceHack** [comment]
Make sure you run npm install before publishing your task
https://github.com/microsoft/azure-pipelines-task-lib/issues/485

**Comment by pinkeshsharma** [comment]
We're facing the same issue, It's breaking our helm CI builds.

**Comment by RobiNino** [comment]
Version 1.10.5 was now released and the issue was fixed.
Please refresh or reinstall the extension if it doesn't automatically update.
We are incredibly sorry about the inconvenience caused by this issue.
