### ISSUE TITLE
ArtifactoryNpm@2 is your task?

### ISSUE THREAD

**Issue by baeron** [jfrog/artifactory-azure-devops-extension#209]
Hi
I find in my code the next code
`        - task: ArtifactoryNpm@2
          inputs:
            command: 'pack and publish'
            artifactoryService: 'XYZ'
            targetRepo: 'XYZ'
          displayName: 'Publish library'`
It is work, but I can't find a description for this task on google
Is your API keyword? If yes, please provide a full description for this task (inputs, custom command).
Thanks.

**Comment by eyalbe4** [comment]
@baeron,
Did you come across the [Artifactory Azure DevOps Extention documentation](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension)?
We would also appreciate any feedback you can provide for it. If you think that we should modify the documentation format or add anything to it, please let us know. 
Thanks

**Comment by baeron** [comment]
@eyalbe4 
I have several Angular libraries that need to be built, packaged, and published on JFROG.
Could you please provide a list of all possible parameters for the task in YAML file how is it implemented in microsoft Azure DevOps documentation 
**- task: Npm@1
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: projectName/feedName
    # other params**

It would help a lot.
Thanks.

**Comment by eyalbe4** [comment]
@baeron,
I think that easiest way to create this YAML, is by using the tasks UI available in Azure DevOps.
Look for the **Artifactory NPM**  task in the list of available tasks, fill out the fields in the UI, and generate the YAML.
Please let me know if you see an issue with this.

**Comment by baeron** [comment]
I work on a large project and I have no way to add your GUI functionality to Azure DevOps.
**Can I link to the .tgz file in
- task: ArtifactoryNpm @ 2
  inputs:
    command: 'publish {[<tarball> | <folder>]}' ???**

**Comment by baeron** [comment]
Full description is [here](https://github.com/jfrog/artifactory-azure-devops-extension/blob/master/tasks/ArtifactoryNpm/Ver2/task.json)
