### ISSUE TITLE
Providing an option to add the distribution service connection and use it in the distribution task

### ISSUE THREAD

**Issue by JayanthSureshjfrog** [jfrog/artifactory-azure-devops-extension#227]
**Problem statement:** Currently in Azure devops extension,  we do not have an option for distribution task, so it would be good to provide an option for the users to add the distribution service connection and use it in the distribution task.
For various reasons, users do not want to go with the below workaround, as they don't want to pass the URL with credentials in JFrog CLI. 

**Workaround:** Use the JFrog CLI with --dist-url and credentials.

**Comment by eyalbe4** [comment]
@JayanthSureshjfrog - 
Version 1.12.0 was released today, and includes a new Distribution task, as well a new JFrog Distribution service connection.
See the [documentation](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension) for more information.
Looking forward to your feedback.
