### ISSUE TITLE
Have JFrog abandoned this extension?

### ISSUE THREAD

**Issue by edrandall** [jfrog/artifactory-azure-devops-extension#232]
JFrog are notable by their absence from here since 1st Jan 2021.
Is this extension still maintained and supported?

**Comment by eyalbe4** [comment]
@edrandall,
We have a lot of features and enhancements planned for this extension.
It is definately maintained and supported, and to the best of my knowledge, currently installed on thousands of Azure DevOps instances.
Please let us know if there's something in particular that you were looking for or needed help with. We'd be more than happy to assist.
