### ISSUE TITLE
Download with explode/extract Artifacts fails when 2 files or more with error The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by mikescr** [jfrog/artifactory-azure-devops-extension#237]
**Describe the bug**
The second file that is downloaded, it uses double target path in its path name and when it tries to copy or explode/extract the task fails with the error "[Error] opening source file: open D:\a\1\s\ui\D:\a\1\s\ui\ModlueName2.UI-2.2.1.zip: The filename, directory name, or volume label syntax is incorrect."

The log from the Download task, I've redacted the filenames and artifactory paths;
Found tool in cache: jfrog 1.46.1 x64
Running jfrog-cli from C:\hostedtoolcache\windows\jfrog\1.46.1\x64\jfrog.exe.
JFrog CLI version: 1.46.1
Generic download...
Using file spec:
{
    "files": [
     {
        "pattern": "[redacted]/*.zip",
        "target": "D:\\a\\1\\s/ui\\",
        "build": "[redacted]",
        "flat":"true",
        "explode":"true"
     }
    ]
}

[Info] Searching items to download...
[Info] [Thread 2] Downloading reponame/dir/ModlueName1-2.2.1.zip
[Info] [Thread 0] Downloading reponame/dir/ModlueName2.UI-2.2.1.zip
[Info] [Thread 0] [1]: 206 Partial Content...
[Info] [Thread 0] [0]: 206 Partial Content...
[Info] [Thread 0] [2]: 206 Partial Content...
[Info] [Thread 2] Extracting archive: D:\a\1\s\ui\ModlueName1-2.2.1.zip to D:\a\1\s\ui\
[Info] [Thread 0] Extracting archive: D:\a\1\s\ui\D:\a\1\s\ui\ModlueName2.UI-2.2.1.zip to D:\a\1\s\ui\
[Error] [Thread 0]  Received an error: opening source file: open D:\a\1\s\ui\D:\a\1\s\ui\ModlueName2.UI-2.2.1.zip: The filename, directory name, or volume label syntax is incorrect.
{
[Error] opening source file: open D:\a\1\s\ui\D:\a\1\s\ui\ModlueName2.UI-2.2.1.zip: The filename, directory name, or volume label syntax is incorrect.
  "status": "failure",
[Error] Download finished with errors, please review the logs.
  "totals": {
    "success": 0,
    "failure": 0
  }
}
##[error]Error: Command failed: C:\hostedtoolcache\windows\jfrog\1.46.1\x64\jfrog.exe rt dl --url="https://aic.jfrog.io/artifactory" --user=*** --password=*** --fail-no-op=true --dry-run=false --insecure-tls=false --threads=3 --retries=3 --validate-symlinks=false --split-count=3 --min-split=5120

**To Reproduce**
Create a task which downloads 2 or more files with flat and explode options set as "true".

**Expected behavior**
Extract downloaded artifacts using the correct target path with flat/explode options.

**Versions**
- Artifactory Azure DevOps extension version: 
| Publisher   |   Installed version | Last updated
| JFrog         |   1.11.5 (Latest)     | Apr 12, 2021 at 7:50 PM GMT+2

- Agent operating system:
Azure Cloud Agent - windows-2019

- JFrog Artifactory version:
Latest SaaS (Cloud)

**Additional context**
Other tasks with a single file artifact with explode option set to true works
Downloading multiple artifacts without exploding works.

Last time it worked, April 6th.
Log from the same task:

Starting: Download Artifacts - UI

Task         : Artifactory Generic Download
Description  : Download artifacts from Artifactory using FileSpecs, while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 3.11.2
Author       : JFrog

Found tool in cache: jfrog 1.42.3 x64
Running jfrog-cli from C:\hostedtoolcache\windows\jfrog\1.42.3\x64\jfrog.exe.
JFrog CLI version: 1.42.3
Generic download...
Using file spec:
{
    "files": [
     {
        "pattern": "[redacted]/*.zip",
        "target": "D:\\a\\1\\s/ui\\",
        "build": "[redacted]",
        "flat":"true",
        "explode":"true"
     }
    ]
}
[Info] Searching items to download...
[Info] [Thread 2] Downloading reponame/dir/ModlueName2.UI-2.2.0.zip 
[Info] [Thread 0] Downloading reponame/dir/ModlueName1-2.2.0.zip
[Info] [Thread 0] Extracting archive: D:\a\1\s\ui\ModlueName1-2.2.0.zip to D:\a\1\s\ui\
[Info] [Thread 2] [0]: 206 Partial Content...
[Info] [Thread 2] [1]: 206 Partial Content...
[Info] [Thread 2] [2]: 206 Partial Content...
[Info] [Thread 2] Extracting archive: D:\a\1\s\ui\ModlueName2.UI-2.2.0.zip to D:\a\1\s\ui\
[Info] [Thread 2] Done downloading.
{
  "status": "success",
  "totals": {
    "success": 2,
    "failure": 0
  }
}

**Comment by gailazar300** [comment]
Thanks for reporting this.
We fixed this issue and it will be released in the next patch.

**Comment by mikescr** [comment]
The issue mentioned above is open for quite a while, we need it to be closed asap, we've been using an older version of the extension which used an older cli version 1.42.3, since the mandatory update yesterday, it stopped, we have many pipelines that use this task. Do I need to escalate it so it be released?

**Comment by eyalbe4** [comment]
@mikescr,
I completely agree. As you can see here - https://github.com/jfrog/jfrog-client-go/pull/323 - the pull request with @gailazar300's is already merged. We'll soon release a patch for jfrog-cli which includes this fix, as well as an Azure DevOps extension which uses the new jfrog-cli patch.

**Comment by eyalbe4** [comment]
@mikescr - 
Patch 1.11.7 is released to the marketplace and includes this fix.
Looking forward to your feedback for the fix.

**Comment by eyalbe4** [comment]
@mikescr -
I'm closing this issue for now, but please let us know if you're still experiencing any issues or need assistance.
