### ISSUE TITLE
Issue with Azure devops Ariifactory  generic download.task.

### ISSUE THREAD

**Issue by koteshbhupathi** [jfrog/artifactory-azure-devops-extension#244]
Greetings Team,

Artifactory generic download unable to use the jfrog cli which was installed by Artifactory tools task.
My Agents in VM restricted to download executable from internet.
please refer attached screenshot.

2021-04-21T12:03:02.3985185Z ##[section]Starting: Artifactory Generic Download
2021-04-21T12:03:02.4470510Z ==============================================================================
2021-04-21T12:03:02.4470936Z Task         : Artifactory Generic Download
2021-04-21T12:03:02.4471629Z Description  : Download artifacts from Artifactory using FileSpecs, while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
2021-04-21T12:03:02.4472252Z Version      : 3.11.8
2021-04-21T12:03:02.4472547Z Author       : JFrog
2021-04-21T12:03:02.4472841Z Help         : 
2021-04-21T12:03:02.4473207Z ==============================================================================
2021-04-21T12:03:03.7367162Z Downloading: https://releases.jfrog.io/artifactory/jfrog-cli/v1/1.46.3/jfrog-cli-windows-amd64/jfrog.exe?bt_package=jfrog-cli-windows-amd64
2021-04-21T12:03:03.7404398Z ##[error]Error occurred while executing task:
Failed while attempting to download JFrog CLI from https://releases.jfrog.io/artifactory/jfrog-cli/v1/1.46.3/jfrog-cli-windows-amd64/jfrog.exe?bt_package=jfrog-cli-windows-amd64. If this build agent cannot access the internet, you may use the 'Artifactory Tools Installer' task, to download JFrog CLI through an Artifactory repository, which proxies https://releases.jfrog.io/artifactory/jfrog-cli/v1/1.46.3/jfrog-cli-windows-amd64/jfrog.exe?bt_package=jfrog-cli-windows-amd64. You may also manually download version 1.46.3 of JFrog CLI and place it on the agent in the following path: C:\azagent\A1\_work\_tool\_jfrog\current\jfrog.exe
Error: read ECONNRESET
2021-04-21T12:03:03.7422428Z ##[section]Finishing: Artifactory Generic Download

**Comment by koteshbhupathi** [comment]
1)Artifactory tools download  task using the agent in  path --->  C:\azagent\A1\_work\_tool\jfrog\1.43.2\x64\jfrog.exe.

2)Artifactory Generic Download task looking for the agent in path ----> C:\azagent\A1\_work\_tool\_jfrog\current\jfrog.exe

why its checking for 2 different Jfrog cli's.

**Comment by RobiNino** [comment]
Hi @koteshbhupathi,
Thanks for reporting this issue.
We are aware of this problem when using a custom version at the tools installer, and are already working on a fix which will be included in our next release.

For now, you should be able to work with the tools installer if you uncheck the "Install custom version".
Sorry for the inconvenience caused by this.

**Comment by koteshbhupathi** [comment]
Hi Rob,

Thanks for your response.
i want to clear two things here .

Before any jfrog tasks in ADO pipeline  i am using Artifactory tool installer (reason because to avoid for any egress firewall restrictions). and the subsequent jfrog steps (example generic download) should use the same jfrog CLI which is downloaded from the step Artifactory tool installer.

when i didnt use any custom version the Artifactory tool installer its failing with in below screenshot.

![image](https://user-images.githubusercontent.com/56534334/115589238-3d0ad100-a2ed-11eb-96c4-7e50d91e2783.png)
![image](https://user-images.githubusercontent.com/56534334/115589518-8f4bf200-a2ed-11eb-834c-f932d7bffca8.png)

**Comment by eyalbe4** [comment]
@koteshbhupathi,
Could it be that the remote repository used by the *Artifactory Tools Installers* task still proxies Bintray? Due to the upcoming sunset of Bintray, new JFrog CLI releases are published to releases.jfrog.io, instead of Bintray. You can configure your remote repository to proxy the new download repository, by following the steps [here](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-ArtifactoryToolsInstaller).
Please let me know if this resolves the issue.

**Comment by koteshbhupathi** [comment]
hi @eyalbe4 

when using the artifactory tool installer with our organization artifactory instance we are not seeing the jfrog-cli version 1.46.3 i think which is why its unable to artifactory tool doesnt download the version.can you advise how do we get the jfrog cli to our artifactory instance

![image](https://user-images.githubusercontent.com/56534334/115617523-1c537300-a30f-11eb-9ba3-df9daa375254.png)

**Comment by eyalbe4** [comment]
@koteshbhupathi,
Did you make sure the remote repository in your organization Artifactory instance proxies the new URL as explained in the link above? I'm pretty sure that's the cause of your issue.

**Comment by koteshbhupathi** [comment]
hi @eyalbe4  i will keep you updated on this.
As i informed the jfrog Admin team..it looks like they raised support ticket with jfrog team after i raised the issue.

**Comment by koteshbhupathi** [comment]
@eyalbe4  thank you very much for your assistance.
The issue has been resolved after 
remote repository used by the Artifactory Tools Installers task still proxies Bintray? Due to the upcoming sunset of Bintray, new JFrog CLI releases are published to releases.jfrog.io, instead of Bintray. You can configure your remote repository to proxy the new download repository, by following the steps

**Comment by eyalbe4** [comment]
Thanks for the update @koteshbhupathi.
Happy to hear the issue is resolved.
