### ISSUE TITLE
Unable to find version '1.0.0' of package 'Microsoft.Web.Infrastructure'.

### ISSUE THREAD

**Issue by Yves-F-A** [jfrog/artifactory-azure-devops-extension#249]
**Describe the bug**
In Azure DevOps Pipelines, I have a 'Artifactory Nuget Restore' task that doesn't work anymore with JFrog CLI version: 1.47.1

**To Reproduce**
In Artifact Repository, I have two versions for 'Microsoft.Web.Infrastructure'
 - Microsoft.Web.Infrastructure.1.0.0.0.nupkg
 - Microsoft.Web.Infrastructure.1.0.0.nupkg

**Expected behavior**
I expected that works as with previous version 1.46.3

**Screenshots**
![image](https://user-images.githubusercontent.com/83455515/116697837-f93a5a80-a9c3-11eb-9626-d1493b9518b8.png)

**Versions**
- Artifactory Azure DevOps extension version: 2.12.0
- Agent operating system: x64
- JFrog Artifactory version: 1.47.1

**Additional context**
To solve or bypass the problem, I added a 'Artifactory Tools Installer' task with specific version 1.46.3 in Azure DevOps Pipelines

**Comment by eyalbe4** [comment]
@Yves-F-A, 
See https://github.com/jfrog/artifactory-azure-devops-extension/issues/248 and let us know if this resolves your issue as well.

**Comment by Yves-F-A** [comment]
Not at all. To solve or bypass the problem, I added a 'Artifactory Tools Installer' task with specific version 1.46.3 in Azure DevOps Pipelines

**Comment by Piksi21** [comment]
> Not at all. To solve or bypass the problem, I added a 'Artifactory Tools Installer' task with specific version 1.46.3 in Azure DevOps Pipelines

Could you please share / screenshot the task you've implemented? We're having a similar problem :|

**Comment by Yves-F-A** [comment]
![image](https://user-images.githubusercontent.com/83455515/116700145-c180e200-a9c6-11eb-837c-cde3767b42e3.png)

**Comment by Piksi21** [comment]
And what about the Service Connection? It fials with 404 error

**Comment by eyalbe4** [comment]
@Yves-F-A / @Piksi21?
How do we reproduce this issue with version 1.47.1 of jfrog-cli? Is there a project I can use to see this failure?

**Comment by Yves-F-A** [comment]
I don't have a problem with Service Connection.

**Comment by Piksi21** [comment]
> I don't have a problem with Service Connection.

I understand but I mean whats the url path in your service connection? o0

**Comment by Yves-F-A** [comment]
It's Azure DevOps Service Connection with Basic Authentication ( Username and Password ) ...
Server URL likes this : https://artifactory.xxx.xxx/artifactory

**Comment by eyalbe4** [comment]
@Yves-F-A,
Following https://github.com/jfrog/artifactory-azure-devops-extension/issues/248 we released version 1.12.1, which sets the NuGet protocol toI v2 as the default for the Artifactory NuGet task, and optionally allows selecting v3. We're not sure whether the issue discussed here is related to that or not.
Are you still experiencing any issues with 1.12.1?

**Comment by Piksi21** [comment]
> @Yves-F-A,
> Following #248 we released version 1.12.1, which sets the NuGet protocol toI v2 as the default for the Artifactory NuGet task, and optionally allows selecting v3. We're not sure whether the issue discussed here is related to that or not.
> Are you still experiencing any issues with 1.12.1?

This fixed the problem for us. Can you provide feedback first as to why the NuGet Protocol tol was changed to v3 in first place and 2) why v3 is causing this issue?

**Comment by eyalbe4** [comment]
@Piksi21,
I'm glad to hear all works for you now.
The decision to change the NuGet protocol to v3 by default came following multiple companies about issues with the v2 protocol. 
We had no idea that this would be a breaking change. All of our teats passed. 
Unfortunately, this turned out to break many builds and we regret this change. The NuGet protocol and NuGet in general are pretty much out of our hands as the maintainers of the Artifactory Azure DevOps extension and JFrog CLI.
We're doing our best to make sure the tools we provide remain stable, while also implementing changes to resolve issues.

**Comment by Piksi21** [comment]
@eyalbe4 Thanks for the reply/feedback & explanation.
