### ISSUE TITLE
Server ID already exists

### ISSUE THREAD

**Issue by elderrollins** [jfrog/artifactory-azure-devops-extension#254]
https://github.com/jfrog/artifactory-azure-devops-extension/blob/ec3a87e5d882eb24b68c5ff16709d84cb13eeab6/artifactory-tasks-utils/utils.js#L663

If I run a pipeline that calls the install task multiple times it will throw an error because it's trying to install using the same pipeline build name, and number as itself. Is there a way to make the install either unique every time, or to allow the user to override the value and pass in their own server ID?

**Comment by RobiNino** [comment]
Hi @elderrollins , 
[This commit](https://github.com/jfrog/artifactory-azure-devops-extension/commit/047e5c2da5043fa8ba1b63fd13278ebe7d9a07b7#diff-8d66cd1e06843efe52c04de686f587d27c4542b2256295dff720a96f5a20e6c9R666), which is included in the latest release (1.12.2), added timestamp to the server ID to make it unique. The same commit also fixed the issue which caused this problem in the first place.
Can you please verify your tasks are running the latest version, or upgrade if this isn't the case?
Thanks

**Comment by RobiNino** [comment]
Hi @elderrollins,
Which install task are you referring to? Is it `Nuget Restore`? 
[This commit](https://github.com/jfrog/artifactory-azure-devops-extension/commit/047e5c2da5043fa8ba1b63fd13278ebe7d9a07b7#diff-8d66cd1e06843efe52c04de686f587d27c4542b2256295dff720a96f5a20e6c9R666), which is included in the latest release (1.12.2), added timestamp to the server ID to make it unique. The same commit also fixed the issue which caused this problem in the first place.
Can you please verify your tasks are running the latest version, or upgrade if this isn't the case?
Thanks

**Comment by elderrollins** [comment]
We are running the most up to date version of the artifactory tools installer task.  
"- task: ArtifactoryToolsInstaller@1"
The error we are seeing when running several calls one after the other is this. 
"[Error] Server ID 'js-npm-bld-20210511.4-forextractorsdownload' already exists.
##[error]Error: Command failed: jfrog c add "js-npm-bld-20210511.4-forextractorsdownload" --artifactory-url="https://<org space>/artifactory" --interactive=false --user=*** --password=***"

**Comment by RobiNino** [comment]
Hi @elderrollins ,
I was able to reproduce the issue. The ToolsInstaller task does not use the mentioned function, so the timestamp addition did not affect it. The issue occurred due to the use of the new CLI config command, which does not override previous configurations. We intend to fix in our next release.

A single use of the ToolsInstaller task is usually sufficient, may I ask what is your use case that required multiple calls?
Thanks

**Comment by elderrollins** [comment]
We have people building several sets of code in the same pipelines, and they may all run on different agents so we have to install the task multiple times. Sometimes though they will run on the same agent multiple times. We also have several pipelines that test specific templates multiple times in a row to catch multiple issues in different environments.

**Comment by RobiNino** [comment]
Hi @elderrollins,
We just release 1.12.3 that includes the fix.
We'd appreciate your feedback for it.
Thanks
