### ISSUE TITLE
Publish Build Info Task (Azure Devops): Specific target repository

### ISSUE THREAD

**Issue by Tobias-08** [jfrog/artifactory-azure-devops-extension#263]
Hi,
the Publish Build Info Task seems to push in the default build repository always. Starting with the new projects we now have a specific build repository. How do I tell the task to push to this repository?

Thanks!

**Comment by eyalbe4** [comment]
Hi @Tobias-Gr,
JFrog Projects support is coming to Azure DevOps in a few weeks time. We'll have a more precise target date soon. You can watch this issue for updates.

**Comment by Biothrawn** [comment]
Hello,
Thank you all for your work. I am having a similar issue to @Tobias-Gr  except I need to have the option to ignore TLS for the build info task. The generic upload has the option, however, Publish Build info does not. I just wanted to see if this will be an option in the future update your talking about. 

Thank you!

**Comment by RobiNino** [comment]
Hi @Tobias-08 ,
Extension version 1.13.0 was just released and includes JFrog Projects support.
All tasks collecting build info should specify the `project key`, along the Publish Build Info Task.
Note JFrog CLI version 1.47.0 or above is required for the projects support.
We'd appreciate your feedback for it.

Hi @Biothrawn ,
Thanks for raising this feature request.
Please open a separate [feature request](https://github.com/jfrog/artifactory-azure-devops-extension/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=) and we will add it to our backlog.
Thanks.

**Comment by Tobias-08** [comment]
Hi @RobiNino ,
thanks!
Unfortunately we are not able to update to 1.13.0. Error message on Azure Devops Server 2020 (version DEV18.M170.8):

"The extension package size '33027250 bytes' exceeds the maximum package size '26214400 bytes'"

**Comment by eyalbe4** [comment]
Thanks for letting us know about this @Tobias-08!
We'll need to reduce the extension package size somehow. We're debating now about the best way to achieve this.

**Comment by Tobias-08** [comment]
@eyalbe4 We managed to bypass the size restriction and updated to 1.13.0.

Now I get an error during 'Publish Build Info' task while using the new project parameter (using CLI V 2.3.0):

```
The system cannot find the file specified.
Command failed: E:\BA\A6\_work\_tool\jfrog\2.3.0\x64\jfrog.exe rt bp [...] --project=[...]
```

Permissions for the build account are fine. Any ideas?

**Comment by eyalbe4** [comment]
Sorry for the late response @Tobias-08!

Version 1.13.1 is released, and the extension size is now reduced.

As for the issue you reported when publishing the build-info, could it be that you set a project key for the **Artifactory Publish Build Info** task, but in the previous tasks, which are set to collected the build-info, the same project key is not configured?
If indeed this is the case, you can set the project key in all the relevant tasks, and the this issue should be fixed.
We definitely should improve the error message logged in this case, and we'll make sure to do so.

**Comment by Tobias-08** [comment]
Thanks. We'll give 1.13.1 a try.

The projectKey was indeed missing in publish. This fixes the issue.
