### ISSUE TITLE
Azure DevOps Extension doesn't support Projects for Release Pipeline Artifacts

### ISSUE THREAD

**Issue by elinafl** [jfrog/artifactory-azure-devops-extension#273]
**Description**
When configuring an Azure DevOps Release pipeline to consume an Artifactory build artifact, it is unable to find the builds within a Project and returns a 404 response that the build is not found. It appears that the [API call](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-AllBuilds) that is being sent does not include a project key and the build list consumption is originating from the global build list only, without having the option to specify a project when choosing the build. 

**To reproduce**
Install the plugin in version 1.13.0 in the Azure DevOps server and configure the connection to the Artifactory server. Then, follow these steps to [use a published artifact in a release](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-UsingPublishedArtifactsinaRelease). When adding an artifact, we need to specify the build, however, the list of builds available includes only the builds configured globally, and not the ones that are a part of a project. 
`Sending HTTP GET request to: https://artifactory-server/artifactory/api/build/build-name/build-number`
`2021-09-16T22:08:21.1104104Z   "errors": [
2021-09-16T22:08:21.1106232Z     {
2021-09-16T22:08:21.1109188Z       "status": 404,
2021-09-16T22:08:21.1110362Z       "message": "No build was found for build name: build-name, build number: build-number "
2021-09-16T22:08:21.1110859Z     }
2021-09-16T22:08:21.1111128Z   ]`

**Expected behavior**
There should be a possibility to choose a project and then view the list of available builds under the selected project. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81092704/134464662-1cecc35b-b19b-4e4f-9cc0-fc1cbaa31310.png)

**Versions**
- Artifactory Azure DevOps extension version: 1.13.0
- Agent operating system: Linux
- JFrog Artifactory version: Any version

**Comment by RobiNino** [comment]
Hey @elinafl ,
We just released extension version 1.13.2 which includes a fix for this bug.
We'd appreciate your feedback for it.
Thanks
