### ISSUE TITLE
Node6 -> Node10 upgrade

### ISSUE THREAD

**Issue by concentralukecollier** [jfrog/artifactory-azure-devops-extension#283]
Hello, we're currently getting a lot of node6 warnings relating to https://github.com/microsoft/azure-pipelines-tasks/issues/15493 we'd be interested to know if this extension will be updated and if so what's the timeline?

Thanks for any correspondence :)

**Comment by HugoVeillette** [comment]
+1, @yahavi @jfrog-ecosystem 
If you could please follow up with an update regarding support of Node 10.

Thank you,

**Comment by RobiNino** [comment]
Hi @concentralukecollier , @HugoVeillette ,
Thanks for raising this request.
We added the upgrade task to our work plan and will update this issue once it is done.

**Comment by iabhee** [comment]
We are seeing this warnings as well on all our pipelines for ArtifactoryDotnetCore, ArtifactoryGenericUpload, ArtifactoryPublishBuildInfo tasks and would be great if you could provide us the approximate timeline. TIA.

**Comment by RobiNino** [comment]
Hi all,
We just released extension version 1.13.3 which migrates to node 10.
Looking forward to your feedback, thanks.

**Comment by andydkelly-ig** [comment]
Thanks @RobiNino - i see the latest version of Artifactory Generic Download task is still version 3 - does this have the update from her on in or will there be a new version of all the tasks published?

**Comment by RobiNino** [comment]
Hi @andydkelly-ig ,
It includes the update. The migration warnings should disappear without further action.

**Comment by andydkelly-ig** [comment]
brilliant thanks for this - and thanks for the speed in which this was resolved.

**Comment by iabhee** [comment]
Thank you so much for quick turnaround on releasing the update @RobiNino. Not seeing the warnings anymore.
