### ISSUE TITLE
Extra properties when uploading a nuget package

### ISSUE THREAD

**Issue by dfal** [jfrog/artifactory-azure-devops-extension#59]
I'm trying to upload a nuget-package with `ArtifactoryNuget` task but can't find a way to add extra properties like `$(Build.SourceVersion)`. Previously with deprecated `jfrog-vso-extension` it was possible.

**Comment by eyalbe4** [comment]
@dfal,
Thanks for sharing this need. We'll make sure to add it. We'll update this issue accordingly.

**Comment by eyalbe4** [comment]
@dfal,
@RobiNino added support for this in https://github.com/jfrog/artifactory-vsts-extension/pull/132
