### ISSUE TITLE
Cannot get "jfrog cli" from "$(Agent.WorkFolder)/_jfrog/current" in a container job

### ISSUE THREAD

**Issue by jeffrey-opdam** [jfrog/artifactory-azure-devops-extension#71]
The "$(Agent.WorkFolder)/_jfrog/current" folder is not available from within a container job.
The $(Agent.WorkFolder) is not mapped during the container initialisation.
Therefore the artifactory tasks cannot find our default cli to use.

Suggestion:
Use $(Agent.ToolsDirectory) folder, which is mapped.

**Comment by mohanrajatnetapp** [comment]
Any update on when this will be fixed? 
https://support.jfrog.com/jFrogCasePage?id=5001r00002eQeTsAAK 
This is stopping rolling out container based build which also has other features which is going along with it.

**Comment by barbelity** [comment]
@jeffrey-opdam @mohanrajatnetapp 
Please check plugin version 1.8.2. 
We have included this fix (#125) to support running container jobs.
It would be great if you can give us a feedback for it.
