### ISSUE TITLE
Generic JFrog CLI Task

### ISSUE THREAD

**Issue by jpreese** [jfrog/artifactory-azure-devops-extension#83]
Similar to other CLI tasks available in Azure DevOps, I see value in adding a JFrog CLI task that takes in an artifactory connection and allows you to run jfrog cli commands.

This allows for end users to have more control over their pipelines, rather than rely on the workflows that are established in the currently existing tasks.

**Comment by eyalbe4** [comment]
Thanks for sharing this requirement @jpreese.
Can you please share more information about how you'd use this functionality? Is there something that you're currently trying to build / set up and cannot accomplish with the existing functionality? This information may help in designing this potential feature, but also other capabilities in the extension.
Thanks!

**Comment by jpreese** [comment]
The need mostly comes from the lack of Go support. If JFrog offered a generic CLI task where I could just fill in the commands and parameters that I would like to run, then I could set up Go using that path.

Though I also see value in just exposing this functionality for general use. I don't think it'd be hard to implement and gives end users greater flexibility in their pipelines.

**Comment by RobiNino** [comment]
Hi @jpreese , 
just letting you know that the latest version (1.7.2) we released this week includes [Go support](https://www.jfrog.com/confluence/display/RTF/Azure+DevOps+and+TFS+Artifactory+Extension#AzureDevOpsandTFSArtifactoryExtension-TriggeringGoBuilds).

**Comment by michaelhuebschmannkuka** [comment]
While Go is now fixed, the Pipeline Tasks always lack the newer features of the cli, would  be great to be able to use the cli with the Azure DevOps service connection as a separate task as requested!

**Comment by eyalbe4** [comment]
@michaelhuebschmannkuka,
Thanks for sharing this requirement!
To help us design the new functionality, can you please share with us the details of the use case? In other words, what are you able to do with JFrog CLI directly, which is currently not supported in Azure DevOps? Does the issue lie in the fact that Azure DevOps is "locked" on a specific JFrog CLI version?

**Comment by michaelhuebschmannkuka** [comment]
one more recent example is upload/download artifacts using filespecs with regex on windows systems. Works with the cli, doesn´t work with the task.

**Comment by eyalbe4** [comment]
Right @michaelhuebschmannkuka - this we're working on removing this restriction as part of the upcoming release of the Azure DevOps Extension.

**Comment by michaelhuebschmannkuka** [comment]
So other Use cases involve Build Promotion (which is flawed with the Azure DevOps tasks in some cases with docker, but works with the cli), setting Properties on Artifacts, testing Distribution, to name a few.
We´ve also already pushed this through the HTS (TFSAP-16).

**Comment by jpreese** [comment]
FWIW I don't really see harm in just exposing a generic JFrog CLI task. I don't think it would be feasible or necessary to try and capture every pipelines use case.

To work around this, we just downloaded the CLI to our agents.

**Comment by eyalbe4** [comment]
A new *JFrog CLI* task has been added in version 1.10.0 of the Artifactory extension.
Than you @liron-shalom for implanting this!
https://github.com/jfrog/artifactory-azure-devops-extension/pull/169
@jpreese and @huebschmann - looking forward to your feedback for it.
