### ISSUE TITLE
Add in way to configure underlying CLI options when downloading Artifacts in a Release Pipeline

### ISSUE THREAD

**Issue by majwang** [jfrog/artifactory-azure-devops-extension#84]
Currently, if you download artifacts in this extension during a release (Artifacts -> Add an artifact -> Artifactory. See https://www.jfrog.com/confluence/display/RTF/Azure+DevOps+and+TFS+Artifactory+Extension#AzureDevOpsandTFSArtifactoryExtension-UsingPublishedArtifactsinaRelease), there is no way to configure cli options such as --threads. There should be an option to do so.

**Comment by AltenTMAOrion** [comment]
We should also be able to set the flat option to false  (cf. file spec). I have a folder as an artifact and it's downloaded flat.

**Comment by eyalbe4** [comment]
@majwang - we can add threads and few other options to the *Genrric Upload* and *Generic Download* tasks. We will add them.

@AltenTMAOrion - are you referring to the download of the build artifacts when setting Atifactory as an artifact source? If so, I'm not sure folders are supported as build artifacts in Artifactory. I may have misunderstood the request. 

Thanks

**Comment by eyalbe4** [comment]
@majwang,
This capability has been recently added. If you tried it and would like to share with us your feedback for it, it'll be great.
Thanks
